DROP TABLE WEAKNESS;
CREATE TABLE WEAKNESS(
  TYPE_ID NUMBER(11),
  WEAKNESS_ID NUMBER(11),
  WEAKNESS_COEFF NUMBER(3,1),
  CONSTRAINT pk_WEAKNESS PRIMARY KEY (TYPE_ID,WEAKNESS_Id)
);

---WEAKNESS FOR TYPE_ID = 1 = 'acier'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,1,0.5); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,2,2); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,6,0.5); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,7,2); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,8,0.5); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,9,0.5); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,10,0.5); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,11,0.5); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,12,0); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,13,0.5); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,14,0.5); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,15,2); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(1,18,0.5); ---vol

---WEAKNESS FOR TYPE_ID = 2 = 'combat'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,2,1); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,6,2); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,7,1); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,8,1); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,9,0.5); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,11,1); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,13,2); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,14,0.5); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,15,1); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,17,0.5); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(2,18,2); ---vol

---WEAKNESS FOR TYPE_ID = 3 = 'dragon'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,2,1); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,3,2); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,4,0.5); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,5,0.5); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,6,2); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,7,0.5); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,8,2); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,9,1); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,11,0.5); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,15,1); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(3,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 4 = 'eau'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,1,0.5); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,2,1); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,4,0.5); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,5,2); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,7,0.5); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,8,0.5); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,9,1); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,11,2); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,15,1); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(4,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 5 = 'electrik'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,1,0.5); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,2,1); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,5,0.5); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,7,1); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,8,1); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,9,1); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,11,1); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,15,2); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(5,18,0.5); ---vol

---WEAKNESS FOR TYPE_ID = 6 = 'fée'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,1,2); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,2,0.5); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,3,0); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,7,1); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,8,1); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,9,0.5); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,11,1); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,12,2); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,15,1); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,17,0.5); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(6,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 7 = 'feu'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,1,0.5); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,2,1); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,4,2); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,6,0.5); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,7,0.5); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,8,0.5); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,9,0.5); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,11,0.5); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,14,2); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,15,2); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(7,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 8 = 'glace'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,1,2); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,2,2); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,7,2); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,8,0.5); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,9,0.5); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,11,1); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,14,2); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,15,1); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(8,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 9 = 'insecte'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,2,0.5); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,7,2); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,8,1); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,9,1); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,11,0.5); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,14,2); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,15,0.5); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(9,18,2); ---vol

---WEAKNESS FOR TYPE_ID = 10 = 'normal'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,2,2); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,7,1); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,8,1); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,9,1); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,11,1); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,15,1); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,16,0); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(10,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 11 = 'plante'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,2,1); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,4,0.5); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,5,0.5); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,7,2); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,8,2); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,9,2); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,11,0.5); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,12,2); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,15,0.5); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(11,18,2); ---vol

---WEAKNESS FOR TYPE_ID = 12 = 'POISON'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,2,0.5); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,6,0.5); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,7,1); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,8,1); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,9,0.5); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,11,0.5); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,12,0.5); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,13,2); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,15,2); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(12,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 13 = 'PSY'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,2,0.5); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,7,1); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,8,1); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,9,2); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,11,1); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,13,0.5); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,15,1); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,16,2); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,17,2); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(13,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 14 = 'ROCHE'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,1,2); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,2,2); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,4,2); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,7,0.5); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,8,2); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,9,1); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,10,0.5); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,11,2); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,12,0.5); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,15,2); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(14,18,0.5); ---vol

---WEAKNESS FOR TYPE_ID = 15 = 'SOL'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,2,1); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,4,2); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,5,0); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,7,1); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,8,2); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,9,1); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,11,2); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,12,0.5); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,14,0.5); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,15,1); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(15,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 16 = 'SPECTRE'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,2,0); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,6,1); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,7,1); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,8,1); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,9,0.5); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,10,0); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,11,1); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,12,0.5); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,15,1); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,16,2); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,17,2); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(16,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 17 = 'TÉNÈBRES'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,2,2); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,5,1); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,6,2); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,7,1); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,8,1); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,9,2); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,11,1); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,13,0); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,14,1); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,15,1); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,16,0.5); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,17,0.5); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(17,18,1); ---vol

---WEAKNESS FOR TYPE_ID = 18 = 'VOL'---
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,1,1); ---acier
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,2,0.5); ---combat
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,3,1); ---dragon
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,4,1); ---eau
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,5,2); ---electrik
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,6,2); ---fée
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,7,1); ---feu
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,8,2); ---glace
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,9,0.5); ---insecte
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,10,1); --- normal
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,11,0.5); ---plante
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,12,1); ---poison
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,13,1); ---psy
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,14,2); ---roche
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,15,0); ---sol
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,16,1); ---spectre
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,17,1); ---ténèbres
INSERT INTO WEAKNESS (TYPE_ID,WEAKNESS_ID,WEAKNESS_COEFF) VALUES(18,18,1); ---vol
