DROP TABLE SPELL;
CREATE TABLE SPELL(
  SPELL_ID NUMBER(11),
  SPELL_NAME VARCHAR2(32),
  SPELL_DESCRIPTION TEXT,
  SPELL_TYPE NUMBER(11),
  SPELL_PP NUMBER(11),
  SPELL_PUIS NUMBER(11),
  SPELL_PREC NUMBER(11),
  SPELL_CLASS VARCHAR2(32),
  SPELL_CT VARCHAR2(32),
  SPELL_CS VARCHAR2(32),
  CONSTRAINT pk_SPELL_ID_PRIMARY_KEY PRIMARY KEY (SPELL_ID),
  CONSTRAINT pk_SPELL_NAME_UNIQUE UNIQUE (SPELL_NAME)
);
