DROP TABLE SPELL;
CREATE TABLE SPELL(
  SPELL_ID NUMBER(11),
  SPELL_NAME VARCHAR(32) CHARACTER SET utf8,
  SPELL_DESCRIPTION TEXT,
  SPELL_TYPE NUMBER(11),
  SPELL_PP NUMBER(11),
  SPELL_PUIS NUMBER(11),
  SPELL_PREC NUMBER(11),
  SPELL_CLASS VARCHAR(32) CHARACTER SET utf8,
  SPELL_CT VARCHAR(32) CHARACTER SET utf8,
  SPELL_CS VARCHAR(32) CHARACTER SET utf8,
  CONSTRAINT pk_SPELL_ID_PRIMARY_KEY PRIMARY KEY (SPELL_ID),
  CONSTRAINT pk_SPELL_NAME_UNIQUE UNIQUE (SPELL_NAME)
);
